services:
  postgres:
    image: postgres:17-alpine
    container_name: postgresnsiago
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nsiago
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - nsiago
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_postgresnsiago
    environment:
      PGADMIN_DEFAULT_EMAIL: juniasdaniel05@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - nsiago

volumes:
  postgres:

networks:
  nsiago: